### PR TITLE
Fix paths for Metropolis

### PR DESCRIPTION
**Pull request by jesse-martinez**

### CODE REVIEW

**Review by ccheetham — CHANGES_REQUESTED** [review]
Please remove the `.DS_Store` and resubmit.

I also note your editor is using tabs in some places.  There is an `.editorconfig` file in the project that your editor seems not to be honoring?

No need to change the tabs in your edits to space in this particular PR.  I'll create a subsequent PR to fix that as there are other tabs usages not of your doing.

**Comment by ccheetham** [comment]
note #120

**Comment by jesse-martinez** [comment]
@ccheetham Okay this should be good to go now

**Review by ccheetham — APPROVED** [review]
lgtm

**Pull request merged**
